vim.keymap.set('n', '<leader>e', vim.cmd.Ex)
vim.keymap.set('n', '<leader>w', vim.cmd.w)
vim.keymap.set('n', '<leader>q', vim.cmd.q)
vim.keymap.set('n', '<leader>nh', vim.cmd.noh)
vim.keymap.set('v', '<leader>/', ':norm i//<CR>')
vim.keymap.set('v', '<leader>-', ':norm i--<CR>')
vim.keymap.set('v', '<leader>#', ':norm i#<CR>')
