vim.keymap.set('n', '<leader>e', ':Ex<CR>')
vim.keymap.set('n', '<leader>w', ':w<CR>')
vim.keymap.set('n', '<leader>q', ':q<CR>')
vim.keymap.set('n', '<leader>nh', ':noh<CR>')
vim.keymap.set('v', '<leader>/', ':norm i//<CR>')
vim.keymap.set('v', '<leader>-', ':norm i--<CR>')
vim.keymap.set('v', '<leader>#', ':norm i#<CR>')
